name: Deploy Laravel to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.KEY }}

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no root@206.189.157.113 << 'EOF'
            cd /var/www/my-laravel-app
            git pull origin main
            docker-compose up --build -d
          EOF
