name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Laravel to DigitalOcean
    runs-on: ubuntu-latest
    
    
    

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      

      - name: Debug SSH Key Output
        run: |
               file ~/.ssh/id_rsa
               echo "${{ secrets.HOST }}"
           
        
      - name: Debug SSH Connection from GitHub Actions
        run: |
             ssh -vvv -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@${{ secrets.HOST }} "echo '✅ SSH Connection Successful from GitHub Actions!'"
             
      - name: Build Laravel Docker Image
        run: |
          docker build -t laravel-app:latest .
          docker save -o laravel-app.tar laravel-app:latest 
          sudo chmod 644 laravel-app.tar # ✅ Ensure correct permissions

      - name: Ensure Target Directory Exists on Server
        uses: appleboy/ssh-action@v0.1.7
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            script: |
              mkdir -p /root/images/
          

      - name: Deploy on DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker load -i /root/laravel-app.tar
            docker stop laravel-app || true
            docker rm laravel-app || true
            docker run -d --name laravel-app -p 80:8000 laravel-app:latest
            docker image prune -f

