name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Laravel to DigitalOcean
    runs-on: ubuntu-latest
    
    
    

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
             mkdir -p ~/.ssh
             echo "${{ secrets.KEY }}" | tr -d '\r' > ~/.ssh/id_server
             chmod 777 ~/.ssh/id_server
             ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

        
      - name: Test SSH Connection
        run: |
          ssh -i ~/.ssh/id_server -o StrictHostKeyChecking=no root@${{ secrets.HOST }} "echo 'SSH Authentication Successful!'"

      - name: Build Laravel Docker Image
        run: |
          docker build -t laravel-app:latest .
          docker save -o laravel-app.tar laravel-app:latest 
          sudo chmod 777 laravel-app.tar # ✅ Ensure correct permissions

      - name: Copy Docker Image to DigitalOcean Droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: laravel-app.tar
          target: /root/
          

      - name: Deploy on DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME}}
          key: ${{ secrets.KEY }}
          script: |
            docker load -i /root/laravel-app.tar
            docker stop laravel-app || true
            docker rm laravel-app || true
            docker run -d --name laravel-app -p 80:80 laravel-app:latest
            docker system prune -af
