name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Laravel to DigitalOcean
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Laravel Docker Image
        run: |
          docker build -t laravel-app:latest .
          docker save -o laravel-app.tar laravel-app:latest
          chmod 644 laravel-app.tar  
          

      - name: Copy Docker Image to DigitalOcean Droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: laravel-app.tar
          target: /root/

      - name: Deploy on DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker load -i /root/laravel-app.tar
            docker stop laravel-app || true
            docker rm laravel-app || true
            docker run -d --name laravel-app -p 80:80 laravel-app:latest
            docker system prune -af
