name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy-nginx-to-server:
    name: deploy-nginx-to-server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Nginx docker image
        run: |
          docker build -f nginxdockerfile -t TEST-docker:0.0.2 .